import Head from 'next/head'
import { excludeKeys } from 'filter-obj'

const obj = {
  a: 'a',
  b: 'b',
}

export default function Home() {
  console.log("Very unique string", excludeKeys(obj, key => key === 'b'))

  return (
    <>
      <Head>
        <title>Bug Repro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Repro {JSON.stringify(excludeKeys(obj, key => key === 'b'))}
      </main>
    </>
  )
}
